version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pets
    volumes:
      - db-data-prod:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      # Use the internal docker network host 'db' so the app connects to the postgres container
      DATABASE_URL: postgresql://postgres:postgres@db:5432/pets
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always

volumes:
  db-data-prod:
