name: CI

on:
  push:
    branches:
      - main
      - feat/**
      - chore/**
  pull_request:
    branches:
      - main

jobs:
  backend-sqlite:
    name: Backend (SQLite)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Run migrations (SQLite)
        env:
          DATABASE_URL: "file:./dev.db"
        run: npx prisma migrate dev --name ci --skip-seed

      - name: Seed database
        run: npx ts-node --transpile-only prisma/seed.ts

      - name: Run tests
        env:
          NODE_ENV: test
        run: npm test -- --runInBand

