name: Lint OpenAPI specs

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  redocly-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install backend dev deps (Redocly CLI)
        run: npm ci

      - name: Lint OpenAPI specs with Redocly
        run: npm run lint:openapi
  spectral-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Spectral
        run: npm i -g @stoplight/spectral-cli

      - name: Lint OpenAPI specs with Spectral
        run: spectral lint -r .spectral.yaml src/openapi.yaml src/openapi-admin.yaml
